export const GAME_CREATED = 'GAME_CREATED';
export const GAME_EXPIRED = 'GAME_EXPIRED';
export const GAME_USER_CONNECTED = 'GAME_USER_CONNECTED';
export const GAME_USER_DISCONNECTED = 'GAME_USER_DISCONNECTED';
