export const GAME_MIN_ALIVE_GAMES_AMOUNT = 200;
// export const GAME_MIN_ALIVE_GAMES_AMOUNT = 1;
export const GAME_USER_TIMEOUT = 15000;
export const GAME_SPIN_DELAY = 8000;
export const GAME_CHECK_DELLAY = 2000;
export const GAME_MIN_CHANCE_TO_WIN = 5;
export const GAME_MAX_CHANCE_TO_WIN = 95;
export const GAME_MAX_ATTEMPTS = 10;
export const GAME_MIN_PRIZE = 1;
export const GAME_MAX_PRIZE = 200;
export const GAME_ADD_BOT_INTERVAL = 2000;
export const GAME_UPDATE_FAKES_INTERVAL = 1800000;
export const GAME_CHECK_ALIVE_GAMES_INTERVAL = 2000;
export const GAME_CHECK_CONNECTED_USERS_INTERVAL = 2000;
export const MIN_PAYMENTS_TO_SHOW = 20;
export const START_USER_BALANCE = 50;
export const REQUIRED_PAID_TO_WITHDRAW = 20;
export const MIN_AMOUNT_OF_WITHDRAWING = 10;
export const GAMES_AMOUNT = 200;
export const MAX_ATTEMPTS = 10;
export const MIN_CHANCE_TO_WIN = 5;
export const MAX_CHANCE_TO_WIN = 95;
export const MIN_PRIZE = 1;
export const MAX_PRIZE = 1000;
export const MIN_AMOUNT_OF_PURCHASE = 1;
export const MAX_AMOUNT_OF_PURCHASE = 5000;

export default {
  REQUIRED_PAID_TO_WITHDRAW,
  MIN_AMOUNT_OF_WITHDRAWING,
  GAMES_AMOUNT,
  MAX_ATTEMPTS,
  MIN_CHANCE_TO_WIN,
  MAX_CHANCE_TO_WIN,
  MIN_PRIZE,
  MAX_PRIZE,
  MIN_AMOUNT_OF_PURCHASE,
  MAX_AMOUNT_OF_PURCHASE,
  GAME_SPIN_DELAY,
};
